site_name: 生物信息实践
site_description: '至少咱还能实践'
site_author: 'pzweuj'
site_url: 'https://pzweuj.github.io/worstpractice'
theme: 
  name: 'material'
copyright: 'Copyright &copy; 2021 pzweuj'

repo_url: https://github.com/pzweuj/pzweuj.github.io/

extra:
  palette:
    primary: 'light blue'

nav:
  - '前言': index.md
  - '一、 DNA-seq' :
    - '01. 参考基因/数据库/原始数据的准备': C01_DNA-seq/01.prepare_data.md
    - '02. 比对': C01_DNA-seq/02.mapping.md
    - '03. 排序以及标记重复序列': C01_DNA-seq/03.sort_and_mark_duplicates.md
    - '04. 找变异': C01_DNA-seq/04.call_snp.md
    - '05. 体细胞突变': C01_DNA-seq/05.call_somatics.md
    - '06. CNV突变': C01_DNA-seq/06.call_cnvs.md
    - '07. 融合基因检测': C01_DNA-seq/07.call_fusions.md
    - '08. 注释': C01_DNA-seq/08.annotation.md
    - '09. 可视化': C01_DNA-seq/09.visualization.md
  - '二、 RNA-seq' :
    - '01. 参考基因/数据库/原始数据的准备': C02_RNA-seq/01.prepare_data.md
    - '02. 比对': C02_RNA-seq/02.mapping.md
    - '03. 计算RPKM/FPKM/TPM/counts': C02_RNA-seq/03.counting.md
    - '04. 差异分析': C02_RNA-seq/04.differential_analysis.md
    - '05. 画图': C02_RNA-seq/05.picture.md
  - '三、 mNGS' :
    - '01. 参考基因/数据库/原始数据的准备': C03_mNGS/01.prepare_data.md
    - '02. 去除宿主基因': C03_mNGS/02.remove_host.md
    - '03. 基因组组装': C03_mNGS/03.assemble.md
    - '04. 宏基因组注释': C03_mNGS/04.annotation.md
    - '05. 可视化': C03_mNGS/05.pictures.md

use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

google_analytics: ['UA-131202162-1', 'auto']

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

